version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 010928215051.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=010928215051.dkr.ecr.ap-south-1.amazonaws.com/spring-demo-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
    - echo Build started on `date`
    - echo Bulding the Jar file
    - mvn clean install
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing to repo
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definition file
    - DOCKER_CONTAINER_NAME=spring-demo-ecr-container
    - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - echo $DOCKER_CONTAINER_NAME
    - echo priting imagedefinitions.json
    - cat imagedefinitions.json 
    - mv target/bike-service-0.0.1-SNAPSHOT.war bike-service-0.0.1-SNAPSHOT.war
artifacts:
  files:
     - imagedefinitions.json
     - target/springboot-aws-deploy.jar
  